version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: {{ cookiecutter.project_slug }}
    container_name: {{ cookiecutter.project_slug }}
    volumes:
      - .:/app:z
    command: /bin/sh -c "while sleep 1000; do :; done"
