site_name: {{ cookiecutter.project_slug }}
theme:
  name: material
  language: 'ja'

nav:
  - Home: index.md

plugins:
{%-   if cookiecutter.use_jupyterlab == "y" %}
  - mkdocs-jupyter
{%-   endif %}

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - "css/extra.css"
extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - "js/extra.js"
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
  search:
    language: 'jp'

markdown_extensions:
  # 目次
  toc:
    permalink: true
  # 注意書きや警告など
  admonition:
  # 数式
  ## '$' もよく使われるが、標準で無効になっているので、明示的に有効にする必要あり
  ## その場合は mdx_math のオプション enable_dollar_delimiter で設定
  ## - mdx_math:
  ##     enable_dollar_delimiter: true
  mdx_math:
  # Font Awesome
  ## mdには :fa-coffee: のように記述
  fontawesome_markdown:
  # 絵文字
  ## material テーマ以外だとサイズが合わないため、 python/name:pymdownx.emoji.to_alt にする
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  # コードハイライト
  pymdownx.highlight:
    use_pygments: true
    noclasses: true
    # https://github.com/pygments/pygments/tree/master/pygments/styles
    pygments_style: default
    linenums: true
  pymdownx.superfences:
    custom_fences:
      # mermaid.js
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
