version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: cookiecutter_cli_poetry_local
    container_name: cookiecutter_cli_poetry_local
    volumes:
      - .:/app:z
    command: /bin/sh -c "while sleep 1000; do :; done"
